// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bankingapp.API.Data;

#nullable disable

namespace bankingapp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bankingapp.API.Entities.Hesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bakiye")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("HesapNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MusteriId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HesapNumarasi")
                        .IsUnique();

                    b.HasIndex("Iban")
                        .IsUnique();

                    b.HasIndex("MusteriId");

                    b.ToTable("Hesaplar");
                });

            modelBuilder.Entity("bankingapp.API.Entities.Islem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("AliciHesapId")
                        .HasColumnType("integer");

                    b.Property<int?>("GonderenHesapId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipi")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AliciHesapId");

                    b.HasIndex("GonderenHesapId");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("bankingapp.API.Entities.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TcKimlikNo")
                        .IsUnique();

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("bankingapp.API.Entities.Hesap", b =>
                {
                    b.HasOne("bankingapp.API.Entities.Musteri", "Musteri")
                        .WithMany("Hesaplar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("bankingapp.API.Entities.Islem", b =>
                {
                    b.HasOne("bankingapp.API.Entities.Hesap", "AliciHesap")
                        .WithMany("AlinanIslemler")
                        .HasForeignKey("AliciHesapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("bankingapp.API.Entities.Hesap", "GonderenHesap")
                        .WithMany("GonderilenIslemler")
                        .HasForeignKey("GonderenHesapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AliciHesap");

                    b.Navigation("GonderenHesap");
                });

            modelBuilder.Entity("bankingapp.API.Entities.Hesap", b =>
                {
                    b.Navigation("AlinanIslemler");

                    b.Navigation("GonderilenIslemler");
                });

            modelBuilder.Entity("bankingapp.API.Entities.Musteri", b =>
                {
                    b.Navigation("Hesaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
